HMSMemri/Controllers/VendorsController.cs
using HMSMemri.BaseSettings;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using hmsBO;
using HMSMemri.Models;
using System.Data;
using Newtonsoft.Json;
using Kendo.Mvc.UI;
using System.Linq;
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Text;
using ClosedXML.Excel;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;

namespace HMSMemri.Controllers
{
    public class VendorsController : IMCPBase
    {
        protected AjaxResult result = new AjaxResult();
        protected DataSourceResult dsResult = new DataSourceResult();
        private readonly IOptions<BaseSettings.ServerVar> _serverVar;
        [Obsolete]
        private readonly IHostingEnvironment _hostingEnvironment;
        protected DataRow mr = null;
        [Obsolete]
        public VendorsController(IOptions<BaseSettings.ServerVar> serverVar, IHostingEnvironment hostingEnvironment) : base(serverVar)
        {
            _serverVar = serverVar;
            _hostingEnvironment = hostingEnvironment;
        }
        #region Index UI
        /// <summary>
        ///   Index page(UI) 
        /// </summary>
        /// <returns></returns>
        public IActionResult Index()
        {
            //Globally to check the login status
            GlobalData userID = GlobalData.GetGlobalSessione(HttpContext.Session, "UserData");
            if (userID?.CurrentUser.UserID == null)
            {
                return RedirectToAction("Index", "Login");
            }
            Global = new GlobalData();
            Global.LastPage = Global.CurPage;
            Global.CurPage = WebPages.customer_aspx;
            PageRight = Rights.Warehouse_Receiving;
            PopUp = false;

            ViewBag.ShowAll = Global.customer_show_closed;
            return View();

        }
        #endregion

        #region Get Vendor page
        /// <summary>
        /// Get Vendor page
        /// </summary>
        /// <param name="request"> Get Vendor page </param>
        /// <returns></returns>
        public ActionResult AddEditVendor(string Id)
        {
            //Globally to check the login status
            GlobalData userID = GlobalData.GetGlobalSessione(HttpContext.Session, "UserData");
            if (userID?.CurrentUser.UserID == null)
            {
                return RedirectToAction("Index", "Login");
            }
            try
            {
                string IDcheck = Id != null ? Encoding.GetEncoding(28591).GetString(Convert.FromBase64String(Id)) : "0";
            }
            catch (Exception)
            {

                return View("~/Views/Shared/Error_EditUrl.cshtml");
            }

            GetVendorResponse response = new GetVendorResponse();
            Vendor vendor = new Vendor();
            DataSet ds = new DataSet();
            List<States> States = new List<States>();
            string VendorID = Id != null ? Encoding.GetEncoding(28591).GetString(Convert.FromBase64String(Id)) : "0";
            int ID = Convert.ToInt32(VendorID);
            try
            {
                //State API call
                DataView dvStates = TableDefs.General.GetStatesForDropDown(ds, true, "* Select One *");
                if (dvStates != null)
                {
                    DataTable dtStates = dvStates.ToTable();
                    for (int i = 0; i < dtStates.Rows.Count; i++)
                    {
                        States state = new States();
                        state.abbr = Convert.ToString(dtStates.Rows[i]["abbr"]);
                        state.st = dtStates.Rows[i]["st"].ToString();
                        States.Add(state);
                    }
                }
                //show selected list item in State
                List<SelectListItem> stateselectionlist = new List<SelectListItem>();
                foreach (var stateItem in States)
                {
                    stateselectionlist.Add(new SelectListItem
                    {
                        Text = stateItem.st.ToString(),
                        Value = stateItem.abbr.ToString()
                    });
                }
                response.StateModule = stateselectionlist;
                GlobalData Global = new GlobalData();
                DataRow Getvendor = TableDefs.Vendor.GetVendors(ds, ID);
                if (Getvendor != null)
                {
                    Global.vendor_id = Utility.ToInt(Getvendor["vendor_id"]);
                    GlobalData.SetGlobalSessione(HttpContext.Session, "vendor_id", Global);
                    GlobalData vendor_id = GlobalData.GetGlobalSessione(HttpContext.Session, "vendor_id");

                    vendor.vendor_id = Utility.ToInt(Getvendor["vendor_id"]);
                    vendor.VendorName = Getvendor["vendor_name"].ToString();
                    vendor.Address1 = Getvendor["address1"].ToString();
                    vendor.Address2 = Getvendor["address2"].ToString();
                    vendor.City = Getvendor["city"].ToString();
                    vendor.State = Getvendor["st"].ToString();
                    vendor.Zip = Utility.FormatZip(Getvendor["zip"].ToString(), true);
                    vendor.Country = Getvendor["country"].ToString();
                    vendor.PhoneNumber = Utility.FormatPhone(Getvendor["phone"].ToString(), true);
                    vendor.FaxNumber = Utility.FormatPhone(Getvendor["fax"].ToString(), true);
                    vendor.EmailAddress = Getvendor["email"].ToString();
                    vendor.Website = Getvendor["website"].ToString();
                    vendor.Notes = Getvendor["notes"].ToString();
                    vendor.IsActive = Convert.ToBoolean(Getvendor["is_active"]);
                }
                else
                {
                    vendor.IsActive = true;
                }

                if (vendor.vendor_id > 0)
                {
                    response.Vendordetail = vendor;
                    response.Statuscode = 1;
                    response.Status = "Success";
                }
                else
                {
                    response.Vendordetail = vendor;
                    response.Status = "New";
                    response.ErrorMessage = "Vendord not found";
                    response.Statuscode = 0;
                }
            }
            catch (System.Exception ex)
            {
                ErrorLog error = new ErrorLog();
                error.errormsg = ex.Message;
                DBAccess.executeSQL("usp_error_log_add", "Main", "Get Vendor/Vendor", error.errormsg);
                HttpContext.Session.SetString("error_log", error.errormsg);
                return RedirectToAction("Error_Log", "Home");
                throw;
            }
            return View(response);
        }
        #endregion

        #region LoadVendorsData
        /// <summary>
        /// LoadVendorsData
        /// </summary>
        /// <param name="request"> Load Vendor Grid</param>
        /// <returns></returns>
        [HttpPost]
        public JsonResult LoadVendorsGrid(bool isactive, bool toggleActive)
        {
            LoadState loadState = new LoadState();
            GetVendorResponse response = new GetVendorResponse();
            GlobalData userID = GlobalData.GetGlobalSessione(HttpContext.Session, "UserData");

            Global = new GlobalData();
            result.success = true;
            DataSet ds = new DataSet();
            try
            {
                // Get Save State in Vendor Grid based the user
                mr = TableDefs.User.GetUserGrid(ds, userID.CurrentUser.UserID, 30);
                if (mr != null)
                {
                    if (mr.Table.Rows.Count > 0)
                    {
                        loadState.usr_id = Utility.ToInt(mr["usr_id"]);
                        loadState.grid_id = Utility.ToInt(mr["grid_id"]);
                        loadState.json_col_ord = mr["json_col_ord"].ToString();
                        response.loadState = loadState;
                        dsResult.Errors = "true";

                    }
                }
                DataView dvFacility = TableDefs.Vendor.GetVendorsList(ds, isactive);
                string jsonData2 = JsonConvert.SerializeObject(ds, Formatting.Indented);
                var listVentory = JsonConvert.DeserializeObject<lst_tbl_vendor>(jsonData2);

                dsResult.Data = listVentory.tbl_vendor.ToList().OrderBy(x => x.vendor_name);
                dsResult.Total = listVentory.tbl_vendor.Count;
            }
            catch (System.Exception ex)
            {

                    ErrorLog error = new ErrorLog();
                    error.errormsg = ex.Message;
                    DBAccess.executeSQL("usp_error_log_add", "Main", " Grid Load/Vendor", error.errormsg);
                    HttpContext.Session.SetString("error_log", error.errormsg);
                    result.success = false;
                    result.message = $"An error occurred retrieving Customer List. {ex.Message}";                
            }

            if (result.success)
            {
                return Json(dsResult);
            }
            else
            {
                return Json(result);
            }           
        }
        #endregion

        #region AddEdit Vendor Functionality
        /// <summary>
        /// AddEdit Vendor Functionality
        /// </summary>
        /// <param name="request"> Save Vendor Details</param>
        /// <returns></returns>
        [HttpPost]
        public GetVendorResponse AddEditVendors(Vendor request)
        {
            int userID = 0;
            GetVendorResponse response = new GetVendorResponse();
            try
            {
                if (ModelState.IsValid)
                {

HMSMemri/Views/Vendors/AddEditVendor.cshtml
@model HMSMemri.Models.GetVendorResponse
@{
ViewData["Title"] = "AddEditVendor";
 Layout = "_Layout";

}
<div class="headertag">
   <a class="header-brand" href="/Customer">
      <svg width="14" height="14" viewBox="0 0 14 14" fill="none" xmlns="http://www.w3.org/2000/svg">
         <path d="M14 8.00009C14 8.55321 13.5531 9.00009 13 9.00009C12.7156 9.00009 12.4562 8.88134 12.275 8.68759L12 8.41571V13.0001C12 13.5532 11.5531 14.0001 11 14.0001H9C8.44687 14.0001 8 13.5532 8 13.0001V10.0001H6V13.0001C6 13.5532 5.55312 14.0001 5 14.0001H3C2.44688 14.0001 2 13.5532 2 13.0001V8.39384L1.74062 8.67196C1.55625 8.87509 1.29375 9.00009 1 9.00009C0.446875 9.00009 0 8.55321 0 8.00009C0 7.73446 0.103125 7.49697 0.26875 7.31572L0.275 7.30946C0.284375 7.30009 0.296875 7.28759 0.30625 7.27821L6.275 1.3001C6.28438 1.29072 6.29375 1.28135 6.30625 1.26885C6.4875 1.09697 6.73125 0.990723 7 0.990723C7.28438 0.990723 7.54063 1.10947 7.72188 1.3001L13.6969 7.28134C13.7031 7.28759 13.7125 7.29697 13.7188 7.30322L13.7281 7.31259C13.8969 7.49384 14 7.73446 14 8.00009Z" fill="#424242" />
      </svg>
   </a>
   <span class="r-arrow">
      <svg width="7" height="10" viewBox="0 0 7 10" fill="none" xmlns="http://www.w3.org/2000/svg">
         <path d="M0.939331 1.06066L4.87871 5.00003L0.939331 8.93944L1.99999 10L6.99999 5.00003L1.99999 0L0.939331 1.06066Z" fill="#424242" />
      </svg>
   </span>
   <a class="header-brand headtagname" href="/Vendors">Vendors</a>
   <span class="r-arrow">
      <svg width="7" height="10" viewBox="0 0 7 10" fill="none" xmlns="http://www.w3.org/2000/svg">
         <path d="M0.939331 1.06066L4.87871 5.00003L0.939331 8.93944L1.99999 10L6.99999 5.00003L1.99999 0L0.939331 1.06066Z" fill="#424242" />
      </svg>
   </span>
   <span class="header-brand headtagname" id="VendorTilte"></span>  
</div>

<div class="row">
    <div class="col-md-12">
        <div class="add-edit-section">
            @using (Html.BeginForm("AddEditVendor", "Vendors", FormMethod.Post, new { enctype = "multipart/form-data", @class = "form-horizontal", id = "AddEdiVendorForm" ,onSubmit = "return SaveVendorForm(this)" }))
            {
                if (@Model.Vendordetail != null && @Model.Vendordetail.vendor_id > 0)
                {
                    <div class="row">
                        <div class="col-lg-6 col-md-6 col-12">
                            <h4 class="form-page-title">Edit Vendor - <span id="VendorNameTitle"></span></h4>
                             <button type="button" class="btn btnDefault " onclick="onChangeVendorContact()">Add Vendor Contact</button>
                        </div>
                    </div>
                }
                else
                {
                     <div class="row">
                        <div class="col-lg-6 col-md-6 col-12">
                            <h4 class="form-page-title">Add Vendor</h4>
                        </div>
                    </div>
                }
                <hr />
                 @Html.HiddenFor(model => model.Vendordetail.vendor_id, new {id="VendorId" })
                 
                 <div class="form-section">
                     <div class="row">
                         <div class="col-lg-6 col-md-6">
                             <div class="form-group">
                                    <label class="col-md-6 control-label"> @Html.DisplayNameFor(model=>model.Vendordetail.VendorName) <span class="spanvalidate"> * </span></label>
                                    <div class="col-md-10">
                                        <div class="input-group">
                                            @Html.TextBoxFor(model => model.Vendordetail.VendorName, new { @class = "form-control col-md-12",id="IsVendorName",tabindex = 1 })
                                            @Html.ValidationMessageFor(Model=>Model.Vendordetail.VendorName,"",new { @class = "text-danger w-100" })  
                                        </div>
                                    </div>
                             </div>
                                <div class="form-group">
                                    <label class="col-md-6 control-label"> @Html.DisplayNameFor(model=>model.Vendordetail.Address1)</label>
                                    <div class="col-md-10">
                                        <div class="input-group">
                                               @Html.TextBoxFor(model => model.Vendordetail.Address1, new { @class = "form-control col-md-12",id="IsAddress1",tabindex = 3 }) 
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-6 control-label"> @Html.DisplayNameFor(model=>model.Vendordetail.Address2)</label>
                                    <div class="col-md-10">
                                        <div class="input-group">
                                               @Html.TextBoxFor(model => model.Vendordetail.Address2, new { @class = "form-control col-md-12",id="IsAddress2",tabindex = 5 }) 
                                        </div>
                                    </div>
                                </div>
                              <div class="form-group">
                                    <label class="col-md-6 control-label"> @Html.DisplayNameFor(model=>model.Vendordetail.City)</label>
                                    <div class="col-md-10">
                                        <div class="input-group">
                                            @Html.TextBoxFor(model => model.Vendordetail.City, new { @class = "form-control col-md-12",id="IsCity",tabindex = 7 })
                                        </div>
                                    </div>
                              </div>
                              <div class="form-group">
                                    <label class="col-md-6 control-label"> @Html.DisplayNameFor(model=>model.Vendordetail.State)</label>
                                    <div class="col-md-10">
                                        <div class="input-group selct-opt">
                                            @Html.DropDownListFor(model => model.Vendordetail.State,Model.StateModule,new { @class = "form-control",id="IsState",  tabindex = 9, Class="status"} )                                            
                                            @Html.ValidationMessageFor(Model=>Model.Vendordetail.State,"",new { @class = "text-danger  w-100" })  
                                        </div>
                                    </div>
                              </div>
                              <div class="form-group">
                                    <label class="col-md-6 control-label">Zip Code</label>
                                    <div class="col-md-10">
                                        <div class="input-group">
                                            @Html.TextBoxFor(model => model.Vendordetail.Zip, new { @class = "form-control col-md-12",@onkeypress = "return isNumberKey(this,event)",id="IsZip",tabindex = 11 })
                                        </div>
                                    </div>
                              </div>
                               <div class="form-group">                                   
                                    <div class="col-md-10">
                                        <div class="input-group flex-nowrap">
                                        @Html.CheckBoxFor(model => model.Vendordetail.IsActive, new { @checked = "checked",id="IsActive"})
                                        <span class="col-md-6 control-label">Active </span>
                                        </div>
                                   </div>
                               </div>
                         </div>
                         <div class="col-lg-6 col-md-6">
                             <div class="form-group">
                                    <label class="col-md-6 control-label"> @Html.DisplayNameFor(model=>model.Vendordetail.PhoneNumber)</label>
                                    <div class="col-md-10">
                                        <div class="input-group">
                                            @Html.TextBoxFor(model => model.Vendordetail.PhoneNumber, new { @class = "form-control col-md-12", data_mask = "000.000.0000",id="IsPhoneNumber",tabindex = 2 })
                                            @Html.ValidationMessageFor(Model=>Model.Vendordetail.PhoneNumber,"",new { @class = "text-danger  w-100" })  
                                        </div>
                                    </div>
                              </div>
                              <div class="form-group">
                                    <label class="col-md-6 control-label"> @Html.DisplayNameFor(model=>model.Vendordetail.FaxNumber)</label>
                                    <div class="col-md-10">
                                        <div class="input-group">
                                            @Html.TextBoxFor(model => model.Vendordetail.FaxNumber, new { @class = "form-control col-md-12", data_mask = "000.000.0000",id="IsFaxNumber",tabindex = 4 })
                                            @Html.ValidationMessageFor(Model=>Model.Vendordetail.FaxNumber,"",new { @class = "text-danger  w-100" })  
                                        </div>
                                    </div>
                              </div>
                              <div class="form-group">
                                    <label class="col-md-6 control-label"> @Html.DisplayNameFor(model=>model.Vendordetail.Website)</label>
                                    <div class="col-md-10">
                                        <div class="input-group">
                                            @Html.TextBoxFor(model => model.Vendordetail.Website, new { @class = "form-control col-md-12",id="IsWebsite",tabindex = 6 })
                                        </div>
                                    </div>
                              </div>  
                              <div class="form-group">
                                    <label class="col-md-6 control-label"> @Html.DisplayNameFor(model=>model.Vendordetail.EmailAddress)</label>
                                    <div class="col-md-10">
                                        <div class="input-group">
                                            @Html.TextBoxFor(model => model.Vendordetail.EmailAddress, new { @class = "form-control col-md-12",id="IsEmail",tabindex = 8 })
                                            @Html.ValidationMessageFor(Model=>Model.Vendordetail.EmailAddress,"",new { @class = "text-danger  w-100" })  
                                        </div>
                                    </div>
                              </div>  
                              <div class="form-group">
                                    <label class="col-md-6 control-label"> @Html.DisplayNameFor(model=>model.Vendordetail.Notes)</label>
                                    <div class="col-md-10">
                                        <div class="input-group">
                                            @Html.TextAreaFor(model => model.Vendordetail.Notes, new { @class = "form-control col-md-12",id="IsNotes",tabindex = 10 })
                                        </div>
                                    </div>
                              </div>  
                         </div>
                     </div>
                    <div class="row">
                        <div class="col-12">                                
                            <input type="submit" value="Save" class="btn btnloginColor" id=btn tabindex="14" />
                        </div>
                    </div>
                 </div>
            }       
        </div>
    </div>
</div>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script type="text/javascript">
    $(document).ready(function () {

   var vendorID=  document.getElementById("VendorId").value;
   if (vendorID == 0 || vendorID ==undefined) {
        $('#VendorTilte').append("Add Vendor");
    }
    else {
        $('#VendorTilte').append("Edit Vendor");
    }
        $('#VendorNameTitle').append($("#IsVendorName").val())
   
    });

    // Only enter the numbers
    function isNumberKey(el, evt) {
           var charCode = (evt.which) ? evt.which : event.keyCode;
           var number = el.value.split('.');

           if (charCode != 46 && charCode > 31 && (charCode < 48 || charCode > 57)) {
               return false;
           }
           //just one dot
           if (number.length > 1 && charCode == 46) {
               return false;
           }
           //get the carat position
           var caratPos = getSelectionStart(el);

           var dotPos = el.value.indexOf(".");
           var maxNum = number[0];
           if (caratPos > dotPos && dotPos > -1 && (number[1].length > 1)) {
               return false;
           }
           return true;
       }
       function getSelectionStart(o) {
           if (o.createTextRange) {
               var r = document.selection.createRange().duplicate()
               r.moveEnd('character', o.value.length)
               if (r.text == '') return o.value.length
               return o.value.lastIndexOf(r.text)
           } else return o.selectionStart
       }
       // Add Vendor Contact Page Link
       function onChangeVendorContact(VendorId) {
            var VendorID = document.getElementById("VendorId").value;
             var link = '@Url.Action("AddEditVendorContact", "VendorContact")';
            link = link.replace("replace", VendorID);
            window.location.href = link;
       }
</script>