HMSMemri/Controllers/CustomerContactController.cs
using HMSMemri.BaseSettings;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using hmsBO;
using HMSMemri.Models;
using System.Collections.Generic;
using Kendo.Mvc.UI;
using System.Data;
using System;
using Newtonsoft.Json;
using System.Linq;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Text;
using Microsoft.AspNetCore.Http;
using System.IO;

namespace HMSMemri.Controllers
{
    public class CustomerContactController : IMCPBase
    {
        private readonly IOptions<BaseSettings.ServerVar> _serverVar;
        protected AjaxResult result = new AjaxResult();
        protected DataSourceResult dsResult = new DataSourceResult();
        public CustomerContactController(IOptions<BaseSettings.ServerVar> serverVar) : base(serverVar)
        {
            _serverVar = serverVar;
        }
        #region Index UI
        public IActionResult Index()
        {
            return View();

        }
        #endregion

        #region  Displaying the edited Customer Contact records
        public IActionResult AddEditContact(string id)
        {
            GetCustomerContactResponse response = new GetCustomerContactResponse();
            CustomerContact contact = new CustomerContact();
            DataSet ds = new DataSet();
            List<CustomerContactDrop> CustomerContactdrop = new List<CustomerContactDrop>();
            GlobalData Global = new GlobalData();
            GlobalData cust_id = GlobalData.GetGlobalSessione(HttpContext.Session, "cust_id");
            GlobalData facility_id = GlobalData.GetGlobalSessione(HttpContext.Session, "facility_id");
            GlobalData Cust_ContactId = GlobalData.GetGlobalSessione(HttpContext.Session, "cust_Contactid");
            try
            {
                string IDcheck = id != null ? Encoding.GetEncoding(28591).GetString(Convert.FromBase64String(id)) : "0";
            }
            catch (Exception)
            {

                return View("~/Views/Shared/Error_EditUrl.cshtml");
            }

            string ContactId = id != null ? Encoding.GetEncoding(28591).GetString(Convert.FromBase64String(id)) : "0";
            int ID = Convert.ToInt32(ContactId);
            try
            {
                if (cust_id != null || Cust_ContactId.cust_id != null)
                {
                    DataRow GetCustomerContact = TableDefs.Customer.GetCustomerContact(ds, ID);
                    if (GetCustomerContact != null)
                    {
                        contact.cust_contact_id = Utility.ToInt(GetCustomerContact["cust_contact_id"]);
                        contact.cust_id = Utility.ToInt(GetCustomerContact["cust_id"]);
                        contact.FirstName = GetCustomerContact["first_name"].ToString();
                        contact.LastName = GetCustomerContact["last_name"].ToString();
                        contact.Title = GetCustomerContact["title"].ToString();
                        contact.PhoneNumber = Utility.FormatPhone(GetCustomerContact["phone"].ToString(), true);
                        contact.CellPhone = Utility.FormatPhone(GetCustomerContact["cell"].ToString(), true);
                        contact.FaxNumber = Utility.FormatPhone(GetCustomerContact["fax"].ToString(), true);
                        contact.EmailAddress = GetCustomerContact["email"].ToString();
                        contact.AltNumber1 = GetCustomerContact["alternate_num1"].ToString();
                        contact.AltNumber2 = GetCustomerContact["alternate_num2"].ToString();
                        contact.ContactType = Utility.ToInt(GetCustomerContact["contact_tp_id"]);
                        contact.Notes = GetCustomerContact["notes"].ToString();
                        contact.ClientPassword = GetCustomerContact["pswd"].ToString();
                        contact.IsActive = Convert.ToBoolean(GetCustomerContact["is_active"]);
                        //contact.ClientLogin = GetCustomerContact["login"].ToString();
                        
                        
                    }
                    else
                    {
                        contact.cust_id = Cust_ContactId.cust_id;
                        contact.IsActive = true;
                    }
                }


                //contact type Drop Down
                DataView dvContact = TableDefs.General.GetContactTypesForDropDown(ds, true, true,"* Select One *");
                if (dvContact != null)
                {
                    DataTable dtContact = dvContact.ToTable();
                    for (int i = 0; i < dtContact.Rows.Count; i++)
                    {
                        CustomerContactDrop status = new CustomerContactDrop();
                        status.contact_tp_id = Utility.ToInt(dtContact.Rows[i]["contact_tp_id"]);
                        status.contact_tp_desc = dtContact.Rows[i]["contact_tp_desc"].ToString();
                        CustomerContactdrop.Add(status);
                    }
                }
                List<SelectListItem> ContactModule = new List<SelectListItem>();
                foreach (var item in CustomerContactdrop)
                {
                    ContactModule.Add(new SelectListItem
                    {
                        Text = item.contact_tp_desc.ToString(),
                        Value = item.contact_tp_id.ToString()
                    });
                }
                response.ContactModule = ContactModule;


                if (contact.cust_contact_id > 0)
                {
                    response.CustomerContactDetail = contact;
                    response.Statuscode = 1;
                    response.Status = "Success";
                }
                else
                {
                    response.CustomerContactDetail = contact;
                    response.Status = "Failure";
                    response.ErrorMessage = " Customer Contact not found";
                    response.Statuscode = 0;
                }
            }

            catch (Exception ex)
            {
                ErrorLog error = new ErrorLog();
                error.errormsg = ex.Message;
                DBAccess.executeSQL("usp_error_log_add", "Main", "Get CustomerContact/CustomerContact", error.errormsg);
                HttpContext.Session.SetString("error_log", error.errormsg);
                response.Statuscode = 0;
                response.Status = "Failure";
                return RedirectToAction("Error_Log", "Home");
            }
            return View(response);  
        }
        #endregion
        
        #region AddEdit Customer Contact
        public GetCustomerContactResponse AddEditCustomerContacts(CustomerContact request)
        {
            CustomerContact contact = new CustomerContact();
            DataSet ds = new DataSet();
            int userID = 0;
            GetCustomerContactResponse response = new GetCustomerContactResponse();
            try
            {
                if (ModelState.IsValid)
                {
                    GlobalData data = GlobalData.GetGlobalSessione(HttpContext.Session, "UserData");
                    if (data != null)
                    {
                        userID = data.CurrentUser.UserID;
                        request.PhoneNumber = Utility.FormatPhone(request.PhoneNumber, false);
                        request.CellPhone = Utility.FormatPhone(request.CellPhone, false);
                        request.FaxNumber = Utility.FormatPhone(request.FaxNumber, false);
                        request.AltNumber1 = Utility.FormatPhone(request.AltNumber1, false);
                        request.AltNumber2 = Utility.FormatPhone(request.AltNumber2, false);
                        if (request.cust_contact_id == 0)
                        {
                            string result = Utility.ToString(DBAccess.executeScalar("usp_cust_contact_new", userID, request.cust_id, request.FirstName, request.LastName, request.Title, request.PhoneNumber, request.CellPhone,
                               request.EmailAddress, request.FaxNumber, request.AltNumber1, request.AltNumber2, request.ContactType,
                                request.Notes, Utility.Encrypt(request.ClientPassword), "", true, request.IsActive));

                        }
                        else
                        {
                            DataRow GetCustomerContact = TableDefs.Customer.GetCustomerContact(ds, request.cust_contact_id);
                            contact.ClientPassword = GetCustomerContact["pswd"].ToString();
                            request.ClientPassword = (request.ClientPassword == contact.ClientPassword) ? request.ClientPassword : Utility.Encrypt(request.ClientPassword);

                            string result = Utility.ToString(DBAccess.executeScalar("usp_cust_contact_update", userID, request.cust_contact_id, request.cust_id, request.FirstName, request.LastName, request.Title, request.PhoneNumber, request.CellPhone,
                                request.EmailAddress, request.FaxNumber, request.AltNumber1, request.AltNumber2, request.ContactType,
                                request.Notes, request.ClientPassword, "", true, request.IsActive));
                        }
                            response.Status = "Success";
                    }
                }
            }
            catch (Exception ex)
            {
                ErrorLog error = new ErrorLog();
                error.errormsg = ex.Message;
                DBAccess.executeSQL("usp_error_log_add", "Main", "Add-Edit/CustomerContact", error.errormsg);
                HttpContext.Session.SetString("error_log", error.errormsg);
                response.Statuscode = 0;
                response.Status = "Failure";
            }
               return response;
        }
        #endregion

        #region Load Contact

        [HttpPost]
        public JsonResult LoadContactGrid(bool isactive, bool toggleActive, int Cust_contactID)
        {

HMSMemri/Views/CustomerContact/Index.cshtml
@{
    ViewData["Title"] = "Customer Contact";
    Layout = "_Layout";
    bool showAll = false;
    bool showAllCustomer = false;
}

<div class="headertag">
    <a class="header-brand" href="/Customer">
        <svg width="14" height="14" viewBox="0 0 14 14" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M14 8.00009C14 8.55321 13.5531 9.00009 13 9.00009C12.7156 9.00009 12.4562 8.88134 12.275 8.68759L12 8.41571V13.0001C12 13.5532 11.5531 14.0001 11 14.0001H9C8.44687 14.0001 8 13.5532 8 13.0001V10.0001H6V13.0001C6 13.5532 5.55312 14.0001 5 14.0001H3C2.44688 14.0001 2 13.5532 2 13.0001V8.39384L1.74062 8.67196C1.55625 8.87509 1.29375 9.00009 1 9.00009C0.446875 9.00009 0 8.55321 0 8.00009C0 7.73446 0.103125 7.49697 0.26875 7.31572L0.275 7.30946C0.284375 7.30009 0.296875 7.28759 0.30625 7.27821L6.275 1.3001C6.28438 1.29072 6.29375 1.28135 6.30625 1.26885C6.4875 1.09697 6.73125 0.990723 7 0.990723C7.28438 0.990723 7.54063 1.10947 7.72188 1.3001L13.6969 7.28134C13.7031 7.28759 13.7125 7.29697 13.7188 7.30322L13.7281 7.31259C13.8969 7.49384 14 7.73446 14 8.00009Z" fill="#424242" />
        </svg>
    </a>
    <span class="r-arrow">
        <svg width="7" height="10" viewBox="0 0 7 10" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M0.939331 1.06066L4.87871 5.00003L0.939331 8.93944L1.99999 10L6.99999 5.00003L1.99999 0L0.939331 1.06066Z" fill="#424242" />
        </svg>
    </span>
    <span class="headtagname">Customer Contact</span>
</div>
<div class="d-flex justify-content-between flex-wrap">
    <div id="AddCustContact" class="flex-grow">
        <div class="d-flex align-items-center flex-wrap">
            <a href="@Url.Action("AddEditContact", "CustomerContact")" class="btn btnDefault newcustomer m-t-15 m-r-4"><svg width="10" height="10" viewBox="0 0 10 10" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M6 4V0H4V4H0V6H4V10H6V6H10V4H6Z" fill="white" /></svg> Add Customer Contact</a>
        </div>
    </div>
                    <div class="d-flex mt-3 c-f-dropdown align-items-center">
                        <div class="customer-dd">
                              <label for="Customers" class="pr-2 mb-0">Customers</label><input class="size-width mr-3" id="customers" /><span class="checkbox"><input name="showAllCustomer" id="showAllCustomer" type="checkbox" @(showAllCustomer ? "checked" : "unchecked") onclick="toggleCheckboxCustomer(this)" class="mr-1" />Include Inactive Customers</span>
                        </div>
                    </div>

 <div class="toolbar d-flex flex-grow-1">
        <div class="right-toolbar-only d-flex align-items-end m-t-15">
            <div class="custom-input-group d-flex flex-wrap flex-sm-nowrap">
                <span class="custom-input-group checkbox-group">
                    <label for="showAll" class="d-flex align-items-center"><input name="showAll" id="showAll" type="checkbox" @(showAll ? "checked" : "unchecked") onclick="toggleCheckbox(this)" /> Include Inactive Contact</label>
                    
                </span>
            </div>
            <div class="custom-input-group search-block">
                <span class="input-group-btn">
                    <input type="text" id="filter" class="form-control search-field" oninput="filter()" placeholder="Search" />
                </span>
            </div>
            <input type="text" class="text-hide" />
        </div>
 </div>
</div>
 <div id="container">
    <div id="gridContact" class="custom-grid m-t-15"></div>
</div>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/js/jquery.loading.block.js"></script>
<script type="text/javascript">

    $(document).ready(function() {

         if((sessionStorage.getItem("IsCustomercontactDropdown")) ==  "true" ){
              $('#showAllCustomer').prop('checked', true);
          }else{
             $('#showAllCustomer').prop('checked', false);
          }
      loadData(false, false);
 

      var dataSource = new kendo.data.DataSource({});
        $("#gridContact").kendoGrid({
            dataSource: dataSource,
            sortable: true,
            resizable: true,
            pageable: {
                refresh: true,
                pageSizes: true,
                buttonCount: 5,
                messages: {
                    itemsPerPage: "Items Per Page"
                },
                pageSizes: [10, 15, 25, 50, 100]
            },
            scrollable: true,
            sortable: true,
            navigatable: true,
            resizable: true,
            reorderable: true,
            filterable: true,
            columnMenu: true,
            groupable: true,
           
            detailExpand: function(e) {
                e.sender.tbody.find('.k-detail-row').each(function(idx, item) {
                    if (item !== e.detailRow[0]) {
                        e.sender.collapseRow($(item).prev());
                    }
                })
            },
          detailCollapse:onDetailCollapse,
            columns: [{
                    field: "first_name",
                    title: "First Name",
                    template: "<a class='anchorNavLinkStyle' href='javascript:void(0)' data-ID='#= cust_contact_id #' onclick='onContactClick(this)'>#=first_name#</a>"
                },
                {
                    field: "last_name",
                    title: "Last Name",
                    attributes: {
                        title: "#=last_name#"
                    }
                },
                {
                    field: "title",
                    title: "Title",
                    attributes: {
                        title: "#=title#"
                    }
                },
                {
                    field: "notes",
                    title: "Notes",
                    attributes: {
                        title: "#=notes#"
                    }
                },
                {
                    field: "phone",
                    title: "Phone",
                    attributes: {
                        title: "#=phone#"
                    }
                },
                {
                    field: "fax",
                    title: "Fax",
                    attributes: {
                        title: "#=fax#"
                    }
                }, 

            ]
        });
    });

     function loadData(isactive, toggleActive) {
          var Cust_contactID = sessionStorage.getItem("cust_Contactid");
           $.loadingBlockShow();                  
       $.ajax({
           type: 'POST',
           url: "/CustomerContact/LoadContactGrid ",
           data: { isactive: isactive,
               toggleActive: toggleActive ,
                Cust_contactID:Cust_contactID},
           pageSize: 10,
           success: function (result) {
               if (result.success == null) {
                   var grid = $("#gridContact").data("kendoGrid");
                   var currPage = grid.dataSource.page();
                   var dataSource = new kendo.data.DataSource({
                       data: result.data,
                       pageSize: 15,
                       page: 0
                   });
                    grid.setDataSource(dataSource);
                    
                   $.loadingBlockHide();
               }
               else {
                   $("#alert_error").text(result.message).show();
                   window.location.href ="/Home/Error_Log";
               }
           }
       });
    }
        function onDetailCollapse(e){
              var grid = $("#gridContact").data("kendoGrid");
                    var expanded = $.map(grid.tbody.children(":has(> .k-hierarchy-cell .k-i-collapse)"), function (row) {
                        return $(row).data("uid");
                    });
                    grid.one("dataBound", function () {
                        grid.expandRow(grid.tbody.children().filter(function (idx, row) {
                            return $.inArray($(row).data("uid"), expanded) >= 0;
                        }));
                    });
                    grid.refresh();
        }

    function onContactClick(arg) {
        $.loadingBlockShow();
        encodedStr = btoa(arg.dataset.id);
        var link = '@Url.Action("AddEditContact", "CustomerContact", new { id = "replace" })';
        link = link.replace("replace", encodedStr);
        window.location.href = link;

    }
     

     function filter() 
     {
           sessionStorage.clear()
           var queryString = $("#filter").val();
           sessionStorage.setItem("search", queryString );

           var grid = $("#gridContact").data("kendoGrid");
           var orfilter = { logic: "or", filters: [] };
           orfilter.filters.push(
               { field: "first_name", operator: "contains", value: queryString },
               { field: "last_name", operator: "contains", value: queryString },
               { field: "title", operator: "contains", value: queryString },
               { field: "notes", operator: "contains", value: queryString },
               { field: "phone", operator: "contains", value: queryString },
               { field: "fax", operator: "contains", value: queryString }               
              
           );
           if (queryString) {
               grid.dataSource.filter(orfilter);
               $.loadingBlockHide();
           } else {
               grid.dataSource.filter({});
               $("#filter").val('');
               grid.dataSource.read();
           }
     }

      
    function toggleCheckbox(arg) {
        $("#showAll").toggleClass('checked');
        const cb = document.querySelector('#showAll');
        loadData((cb.checked), false);
        document.getElementById('filter').value = '';
    }

      $(document).ready(function() {
        //Contracts  grid load      
        loadData(false, false);
          $("#AddCustContact").hide();         
        // Dropdown for customer
       
          if(sessionStorage.getItem("IsCustContact_checked") == "true"){
             $('#showAllCustomer').prop('checked', true);
          }
           $("#showAllCustomer").toggleClass('checked');
           const cb = document.querySelector('#showAllCustomer');
           LoadCustomerDropdowns(cb.checked,true);
        // Check the CustID and facility id based the Add Customer Contact  Hide and Show
        if (sessionStorage.getItem("cust_Contactid") != null && sessionStorage.getItem("cust_Contactid") != 0  ) {
            $("#customers").val(sessionStorage.getItem("cust_Contactid"));   
             //$('#showAllCustomer').prop('checked', true);
                loadData(false, false);
                 $("#AddCustContact").show();                   
        }
        else if (sessionStorage.getItem("cust_Contactid") == 0 && sessionStorage.getItem("cust_Contactid") == null ) {
            loadData(false, false);
            $("#AddCustContact").hide();            
        }


    });
    //Customer Dropdown
    function LoadCustomerDropdowns(isactive, toggleActive) {
          
        $.ajax({
            type: 'POST',
            url: "/Customer/LoadCustomerDropdown",
            data: { isactive: isactive, toggleActive: toggleActive },
            pageSize: 10,
            success: function(result) {
                if (result.errors == "true") {
                }
                if (result.success == null) {
                    var dataSource = new kendo.data.DataSource({
                        data: result.data,
                    });
                    if (result.data.filter(x=>x.cust_id == sessionStorage.getItem("cust_Contactid")).length == 0) {
                        sessionStorage.setItem("cust_Contactid", 0);
                        $("#AddCustContact").hide(); 
                        loadData(false, false);
                    }

                    $("#customers").kendoDropDownList({
                        dataSource: dataSource.options.data,
                        dataTextField: "cust_name",
                        dataValueField: "cust_id",
                        //Change Event
                         
                        change: function(e) {
                            var value = this.value();
                            sessionStorage.setItem("cust_Contactid", value);
                              $("#AddCustContact").show(); 
                            loadData(false, false);
                            if (sessionStorage.getItem("cust_Contactid") == 0) {
                                loadData(false, false);
                               $("#AddCustContact").hide();  
                            }
                        }
                    });
                }
                else {
                    $("#alert_error").text(result.message).show();
                }
            }
        });
    }

       
   function toggleCheckboxCustomer(arg) {
       $("#showAllCustomer").toggleClass('checked');
       const cb = document.querySelector('#showAllCustomer');
       sessionStorage.setItem("IsCustContact_checked", (cb.checked));
       LoadCustomerDropdowns((cb.checked), false);
    }
</Script>